### ISSUE TITLE
Problem during pcap analysis..

### ISSUE THREAD

**Issue by ZikyHD** [omriher/CapTipper#4]
unsupported operand type(s) for &: 'str' and 'int'

**Comment by ZikyHD** [comment]
http://www.mediafire.com/download/avabg54tzqvysb6/split_00000_20130220220148.pcap

**Comment by ZikyHD** [comment]
...reading my msg it's seems to be quite rude :) So i have to say i really appreciate your prog!!! and my first impression was...waouh....then i type 'hosts'...waouh!!!! :))

**Comment by omriher** [comment]
Hi,
Don't worry about it :)

It seems that there currently is a problem handling some next generation pcap files (pcapng) in the pcap-parser library.
As a temporary solution, I would advise you to convert the pcap file to the original format (you can do that using wireshark) Until this would be resolved.

Thanks for reporting the bug.

**Comment by ZikyHD** [comment]
...and thank you for the quick answer! i will try this ;-)

**Comment by omriher** [comment]
Bug resolved thanks to @gr.
Fix can be found here https://github.com/omriher/CapTipper/commit/5c4effad596249c86fd2c2485509dddd52c22194
