### ISSUE TITLE
Issues reading pcap files created with VirtualBox

### ISSUE THREAD

**Issue by eldraco** [omriher/CapTipper#5]
Hi, thanks for this great tool!

I'm having some issues reading pcap files generated by Virtualbox. 

For example the pcap file: 
https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-14/2013-10-18_capture-win15.pcap

./CapTipper.py 2013-10-18_capture-win15.pcap 1234
CapTipper v0.1 - Malicious HTTP traffic explorer tool
Copyright 2015 Omri Herscovici omriher@gmail.com

[A] Analyzing PCAP: 2013-10-18_capture-win15.pcap
unpack requires a string argument of length 14

The issue is that there is a first (maybe broken) packet in the pcap file that is stopping the parser. To temporary solve this issue I must delete the first packet in the pcap file, with the following command:

`editcap 2013-10-18_capture-win15.pcap 2013-10-18_capture-win15.NEW.pcap 1`

Usually tcpdump/wireshark ignore this type of situation so you can read the pcap files. Not sure why.
Maybe there is a way of telling CapTipper to ignore it also?

thanks
sebas

**Comment by omriher** [comment]
Hi,
Good catch.
I believe this fixed it https://github.com/omriher/CapTipper/commit/55b95a2a5c05c3a56615db75f588761388c95508

Thanks!
