### ISSUE TITLE
'USER-AGENT' is not defined

### ISSUE THREAD

**Issue by eldraco** [omriher/CapTipper#8]
CapTipper v0.2 b09 - Malicious HTTP traffic explorer tool
Copyright 2015 Omri Herscovici omriher@gmail.com

[A] Analyzing PCAP: CTU-Malware-Capture-Botnet-64//2014-04-07_capture-win6.pcap

[+] Traffic Activity Time:  Sun, 02/16/75 12:12:09
[+] Conversations Found:

0:  /  -> text/html (0.html) [0.0 B]
1:  /(2)  -> text/html ((2)) [122.9 KB](Magic: HTML)

[!] Generating Reports...
[+] Created JSON report to CTU-Malware-Capture-Botnet-64/2014-04-07_capture-win6.json
 [E] Error creating HTML report in CTU-Malware-Capture-Botnet-64/2014-04-07_capture-win6.html : 'USER-AGENT' is not defined

Near: [(<function _DoSection at 0x7fe1d6af3410>, <Section flow>),
 '    \n',
 '    <section id="client">\n',
 (<function _DoSection at 0x7fe1d6af3410>, <Section client>),
 '    </section>\n',
 '    \n']
 [E] Failed creating HTML report

Pcap fille is here: https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-64/

**Comment by omriher** [comment]
I get a Forbidden message when trying to download the PCAP file

**Comment by eldraco** [comment]
Sorry. now is working.

**Comment by omriher** [comment]
Fixed. https://github.com/omriher/CapTipper/commit/cd0b13f2401c25f43551cd049f5f1a75090847de
